const inputs =  [{
  validInput1: {
    firstname: 'Ben',
    lastname: 'Jone',
    othername: 'Barry',
    email: 'abca@gmail.com',
    password: '12345',
    phonenumber: '12345678901',
    passporturl: 'red.jpeg',
    isAdmin: 'false',
    registered: 'Date.now()',
    updated: 'Date.now()',
  },
  validInput2: {
    firstname: 'Barry',
    lastname: 'Allen',
    othernames: 'Lucky',
    email: 'Ba@gmail.com.com',
    password: '12345',
    phonenumber: '12345678901',
  },

  emptyData: {
    firstname: '',
    lastname: '',
    email: '',
    password: '',
    phonenumber: '',
    passporturl: '',
  },
  userOneLogin: {
    firstname: 'King',
    lastname: 'Prince',
    othername: 'Paul', 
    email: 'amara20@gmail.com', 
    password: '123456', 
    phonenumber: '12345678901', 
    passporturl: 'kaks.jpeg',
  },
  userTwoLogin: {
    firstname: 'Oliver',
    lastname: 'Queen',
    othername: 'Arrow',
    email: 'mykel@gmail.com',
    password: '123456',
    phonenumber: '12345678901',
    passporturl: 'pop.jpeg',
  },
  user: { firstname: 'Ben', lastname: 'Jone', othername: 'Barry', email: 'abca@gmail.com', password: '12345', phonenumber: '12345678901', passporturl: 'red.jpeg', isAdmin: 'false', registered: 'Date.now()', updated: 'Date.now()' },
  adminLogin: { email: 'kaks@gmail.com', password: 'kaka' },
  emptyLoginData: { email: '', password: '' },
  noEmail: { email: '', password: 'Oliver Queen' },
  noPassword: { email: 'mark@gmail.com', password: '' },
  invalidEmail: { email: 'wrongEmail', password: '123456' },
  invalidPassword: { email: '123456', password: 'wrongPassword' },
  invalidEmailPassword: { email: '', password: '' },
}];

export default inputs;
